# Fix Gene Display - Comprehensive Solution
# Fix both table display and add hover tooltips

library(stringr)
library(dplyr)

cat("=== Fixing Gene Display Issues ===\n")

# 1. First, analyze the actual data structure to understand lookup parameters
cat("1. Analyzing gene association data structure...\n")
data <- readRDS("inst/extdata/gene_term_associations.rds")

cat("   Available analysis types:", paste(unique(data$analysis_type), collapse = ", "), "\n")
cat("   Available genes:", paste(unique(data$gene), collapse = ", "), "\n")
cat("   Available clusters:", paste(unique(data$cluster), collapse = ", "), "\n")
cat("   Available enrichment types:", paste(unique(data$enrichment_type), collapse = ", "), "\n")
cat("   Available directions:", paste(unique(data$direction), collapse = ", "), "\n")

# Sample composite keys to understand format
sample_keys <- head(data$composite_key, 3)
cat("   Sample composite keys:\n")
for (i in 1:3) {
  cat("     ", sample_keys[i], "\n")
}

# 2. Create enhanced visualization module with proper gene display and hover tooltips
cat("\n2. Creating enhanced visualization module...\n")

# Read current module
viz_file <- "inst/shiny/modules/mod_visualization_enhanced.R"
viz_content <- readLines(viz_file)

# Create the enhanced version with both table genes and hover tooltips
enhanced_viz_content <- c(
  "# Module: Enhanced Visualization with Gene Display",
  "# Advanced visualizations with integrated gene lists in both tables and tooltips",
  "",
  "mod_visualization_ui <- function(id) {",
  "  ns <- NS(id)",
  "  ",
  "  sidebarLayout(",
  "    sidebarPanel(",
  "      width = 3,",
  "      h4(\"Visualization Settings\"),",
  "      ",
  "      # Conditional UI based on enrichment type",
  "      conditionalPanel(",
  "        condition = \"output.is_gsea == false\",",
  "        ns = ns,",
  "        ",
  "        selectInput(ns(\"plot_type\"),",
  "                    \"Visualization Type:\",",
  "                    choices = list(",
  "                      \"Dot Plot\" = \"dotplot\",",
  "                      \"Bar Plot\" = \"barplot\",",
  "                      \"Lollipop Plot\" = \"lollipop\"",
  "                    ),",
  "                    selected = \"dotplot\"),",
  "        ",
  "        numericInput(ns(\"top_terms\"),",
  "                     \"Number of Top Terms:\",",
  "                     value = 20,",
  "                     min = 5,",
  "                     max = 50,",
  "                     step = 5),",
  "        ",
  "        br(),",
  "        ",
  "        selectInput(ns(\"x_axis\"),",
  "                    \"X-axis:\",",
  "                    choices = c(\"-log10(p.adjust)\" = \"neg_log10_pval\",",
  "                              \"Fold Enrichment\" = \"FoldEnrichment\", ",
  "                              \"Gene Count\" = \"Count\",",
  "                              \"Gene Ratio\" = \"GeneRatio\",",
  "                              \"Rich Factor\" = \"RichFactor\"),",
  "                    selected = \"neg_log10_pval\"),",
  "        ",
  "        selectInput(ns(\"color_by\"),",
  "                    \"Color By:\",",
  "                    choices = c(\"-log10(adjusted p-value)\" = \"p-value\", ",
  "                               \"Fold Enrichment\" = \"Fold Enrichment\"),",
  "                    selected = \"p-value\"),",
  "        ",
  "        checkboxInput(ns(\"show_labels\"),",
  "                      \"Show Labels\",",
  "                      value = TRUE),",
  "        ",
  "        checkboxInput(ns(\"show_genes_in_hover\"),",
  "                      \"Show Genes in Hover\",",
  "                      value = TRUE)",
  "      ),",
  "      ",
  "      # GSEA-specific settings",
  "      conditionalPanel(",
  "        condition = \"output.is_gsea == true\",",
  "        ns = ns,",
  "        ",
  "        selectInput(ns(\"gsea_plot_type\"),",
  "                    \"GSEA Plot Type:\",",
  "                    choices = list(",
  "                      \"Enrichment Plot\" = \"gseaplot\",",
  "                      \"Dot Plot\" = \"dotplot\",",
  "                      \"Ridge Plot\" = \"ridgeplot\",",
  "                      \"GSEA Table\" = \"table\"",
  "                    ),",
  "                    selected = \"gseaplot\"),",
  "        ",
  "        conditionalPanel(",
  "          condition = \"input.gsea_plot_type == 'gseaplot'\",",
  "          ns = ns,",
  "          ",
  "          selectInput(ns(\"gsea_term_select\"),",
  "                      \"Select Gene Set:\",",
  "                      choices = NULL),",
  "          ",
  "          checkboxInput(ns(\"gsea_show_pval\"),",
  "                        \"Show p-value on plot\",",
  "                        value = TRUE),",
  "          ",
  "          checkboxInput(ns(\"gsea_show_running\"),",
  "                        \"Show running score\",",
  "                        value = TRUE),",
  "          ",
  "          sliderInput(ns(\"gsea_base_size\"),",
  "                      \"Base font size:\",",
  "                      min = 8,",
  "                      max = 16,",
  "                      value = 11,",
  "                      step = 1)",
  "        ),",
  "        ",
  "        conditionalPanel(",
  "          condition = \"input.gsea_plot_type != 'gseaplot'\",",
  "          ns = ns,",
  "          ",
  "          numericInput(ns(\"gsea_top_terms\"),",
  "                       \"Number of Top Terms:\",",
  "                       value = 20,",
  "                       min = 5,",
  "                       max = 50,",
  "                       step = 5)",
  "        )",
  "      ),",
  "      ",
  "      br(),",
  "      helpText(\"Plot updates automatically when you change global settings\"),",
  "      helpText(\"Gene lists are shown in Plot Details table and hover tooltips (if enabled)\"),",
  "      ",
  "      br(),",
  "      downloadButton(ns(\"download_plot\"), \"Download Plot\",",
  "                     class = \"btn-success\", style = \"width: 100%;\")",
  "    ),",
  "    ",
  "    mainPanel(",
  "      width = 9,",
  "      tabsetPanel(",
  "        id = ns(\"main_tabs\"),",
  "        selected = \"primary\",",
  "        ",
  "        tabPanel(\"Primary Plot\",",
  "                 value = \"primary\",",
  "                 br(),",
  "                 conditionalPanel(",
  "                   condition = \"output.is_gsea == false\",",
  "                   ns = ns,",
  "                   plotlyOutput(ns(\"interactive_plot\"), height = \"700px\") %>%",
  "                     withSpinner(color = \"#0073b7\")",
  "                 ),",
  "                 conditionalPanel(",
  "                   condition = \"output.is_gsea == true\",",
  "                   ns = ns,",
  "                   plotOutput(ns(\"gsea_plot\"), height = \"700px\") %>%",
  "                     withSpinner(color = \"#0073b7\")",
  "                 )),",
  "        ",
  "        tabPanel(\"Plot Details\",",
  "                 value = \"details\",",
  "                 br(),",
  "                 div(",
  "                   style = \"background-color: #e8f4fd; padding: 10px; border-radius: 5px; margin-bottom: 15px;\",",
  "                   icon(\"info-circle\", style = \"color: #0073b7;\"),",
  "                   strong(\" Gene Lists: \", style = \"color: #0073b7;\"),",
  "                   \"Each enrichment term shows its associated DE genes in the table below.\"",
  "                 ),",
  "                 verbatimTextOutput(ns(\"plot_info\")),",
  "                 br(),",
  "                 DT::dataTableOutput(ns(\"plot_data\")))",
  "      )",
  "    )",
  "  )",
  "}"
)

# Add the server function with comprehensive gene integration
server_content <- c(
  "",
  "mod_visualization_server <- function(id, global_selection, enrichment_data) {",
  "  moduleServer(id, function(input, output, session) {",
  "    ns <- session$ns",
  "    ",
  "    # Enhanced gene association loading with better error handling",
  "    gene_associations_loaded <- reactiveVal(FALSE)",
  "    ",
  "    observe({",
  "      tryCatch({",
  "        # Try multiple approaches to load gene associations",
  "        if (requireNamespace('iSCORE.PDecipher', quietly = TRUE)) {",
  "          iSCORE.PDecipher::load_gene_associations()",
  "          gene_associations_loaded(iSCORE.PDecipher::gene_associations_available())",
  "        } else {",
  "          # Development mode",
  "          source('../../R/gene_association_lookup.R')",
  "          load_gene_associations()",
  "          gene_associations_loaded(gene_associations_available())",
  "        }",
  "        message('Gene associations loaded: ', gene_associations_loaded())",
  "      }, error = function(e) {",
  "        message('Failed to load gene associations: ', e$message)",
  "        gene_associations_loaded(FALSE)",
  "      })",
  "    })",
  "    ",
  "    # Function to get genes for a term with flexible parameter matching",
  "    get_genes_for_term_flexible <- function(term_id, current_selection) {",
  "      if (!gene_associations_loaded()) return('Gene data unavailable')",
  "      ",
  "      # Try exact match first",
  "      result <- tryCatch({",
  "        get_genes_for_term(",
  "          term_id = term_id,",
  "          analysis_type = current_selection$analysis_type,",
  "          gene = current_selection$gene,",
  "          cluster = current_selection$cluster,",
  "          enrichment_type = current_selection$enrichment_type,",
  "          direction = current_selection$direction,",
  "          experiment = 'default'",
  "        )",
  "      }, error = function(e) NULL)",
  "      ",
  "      if (!is.null(result) && !is.null(result$genes)) {",
  "        return(result$genes)",
  "      }",
  "      ",
  "      # Fallback: search for any match with this term ID",
  "      data <- readRDS('../../inst/extdata/gene_term_associations.rds')",
  "      matches <- data[data$term_id == term_id, ]",
  "      if (nrow(matches) > 0) {",
  "        genes <- unlist(strsplit(matches$associated_genes[1], '/'))",
  "        return(genes)",
  "      }",
  "      ",
  "      return(NULL)",
  "    }",
  "    ",
  "    # Function to format gene list for display",
  "    format_gene_list <- function(genes, max_genes = 20) {",
  "      if (is.null(genes) || length(genes) == 0) return('No genes found')",
  "      ",
  "      if (length(genes) <= max_genes) {",
  "        return(paste(genes, collapse = ', '))",
  "      } else {",
  "        displayed_genes <- head(genes, max_genes)",
  "        remaining <- length(genes) - max_genes",
  "        return(paste0(paste(displayed_genes, collapse = ', '), ', ... ', remaining, ' more'))",
  "      }",
  "    }",
  "    ",
  "    # Function to format gene list for hover tooltips",
  "    format_gene_list_hover <- function(genes, max_genes = 15, genes_per_line = 6) {",
  "      if (is.null(genes) || length(genes) == 0) return('No genes found')",
  "      ",
  "      # Limit to max_genes for hover display",
  "      display_genes <- head(genes, max_genes)",
  "      ",
  "      # Split into lines of genes_per_line each",
  "      gene_lines <- split(display_genes, ceiling(seq_along(display_genes) / genes_per_line))",
  "      formatted_lines <- sapply(gene_lines, function(line) paste(line, collapse = ', '))",
  "      ",
  "      result <- paste(formatted_lines, collapse = '<br>')",
  "      ",
  "      # Add count and 'more' info if needed",
  "      if (length(genes) > max_genes) {",
  "        remaining <- length(genes) - max_genes",
  "        result <- paste0(result, '<br>... ', remaining, ' more')",
  "      }",
  "      ",
  "      return(paste0('Genes (', length(genes), '):<br>', result))",
  "    }"
)

# Continue with the rest of the server function...
# This is getting long, let me create the file in parts

# Write the UI part first
writeLines(enhanced_viz_content, "temp_viz_ui.R")

cat("✅ Created enhanced UI with gene display features\n")

# Create the full server content separately
cat("Creating enhanced server content...\n")